### PR TITLE
Add `toJSON` filter

### PR DESCRIPTION
**Pull request by LeviPesin**
Accidentally closed the previous PR 😅 

This PR adds a filter for converting a string to an object, which, I think, is very useful for working with complex data stored as an environment variable.

/ping @saghul

### CODE REVIEW

**Review by saghul — APPROVED** [review]

**Comment by saghul** [comment]
Looks like the qjsc you compiled was not compiled the same way as njk. Did you use the Makefile here to compile qjsc or did you build it yourself?

**Comment by LeviPesin** [comment]
I wasn't able to make `make gen` to work (see https://github.com/saghul/njk/pull/5), so I just used the commands from before the https://github.com/saghul/njk/commit/913dff0d385aaf6d17449a563e0dee4882a0587c -- `make -C quickjs qjsc -j4 && quickjs/qjsc -c -o main-js.c -N mainjs main.js`. Can you please tell me the correct approach?

**Comment by LeviPesin** [comment]
Should be updated again now (with `make && make gen`).

**Review by saghul — APPROVED** [review]

**Comment by LeviPesin** [comment]
Hm... I get the error that the filter is missing even with this PR (when `make`ing executable on my branch and running it on a template using it):
```
Template render error: (/nginx-configs-templates/http.conf)
  Error: filter not found: toJSON
    at _prettifyError (nunjucks.js:116)
    at <anonymous> (nunjucks.js:3505)
    at root (<input>:179)
    at render (nunjucks.js:3522)
    at <anonymous> (nunjucks.js:3308)
    at createTemplate (nunjucks.js:3257)
    at handle (nunjucks.js:3269)
    at <anonymous> (nunjucks.js:3281)
    at next (nunjucks.js:408)
    at asyncIter (nunjucks.js:414)
    at getTemplate (nunjucks.js:3283)
    at render (nunjucks.js:3310)
    at <anonymous> (main.js:84)
```

**Comment by saghul** [comment]
How does your template look like?

**Comment by LeviPesin** [comment]
`toJSON` is used in two places there like so:
```
{% if env.NGINX_WEBSOCKETS %}
{% for name, regexp, backend in env.NGINX_WEBSOCKETS | toJSON %}
upstream {{ name }}_backend {
	random;
	zone {{ name }} 64k;
	server {{ backend }};
}
{% endfor %}
{% endif %}
```
```
{% if env.NGINX_WEBSOCKETS %}
# websocket - forward to the JS server
{% for name, regexp, backend in env.NGINX_WEBSOCKETS | toJSON %}
location ~ "{{ regexp }}" {
	include websocket.conf;
	proxy_pass http://{{ name }}_backend;
}
{% endfor %}
{% endif %}
```

**Comment by saghul** [comment]
I'll give it a go tonight if I have the chance.

**Comment by LeviPesin** [comment]
> I get the error that the filter is missing even with this PR (when makeing executable on my branch and running it on a template using it)

@saghul Do you have any ideas what could be the cause?

**Comment by LeviPesin** [comment]
@saghul ?

**Comment by saghul** [comment]
Sorry I was traveling back from a conference. I'll take a look shortly.

**Comment by saghul** [comment]
I got it working as follows:

Template:

```
{% if env.NGINX_WEBSOCKETS %}
{% for item in env.NGINX_WEBSOCKETS | toJSON %}
upstream {{ item.name }}_backend {
	random;
	zone {{ item.name }} 64k;
	server {{ item.backend }};
}
{% endfor %}
{% endif %}

```

Test:

```
$ NGINX_WEBSOCKETS='[{"name":"foo","regex":"a.*","backend":"1.1.1.1"},{"name":"bar","regex":"b.*","backend":"2.2.2.2"}]' ./build/njk-darwin-arm64 t.njk


upstream foo_backend {
	random;
	zone foo 64k;
	server 1.1.1.1;
}

upstream bar_backend {
	random;
	zone bar 64k;
	server 2.2.2.2;
}
```

**Comment by LeviPesin** [comment]
That seems to work, thank you!!!

**Comment by saghul** [comment]
Now I only need to redo the release procedure be sure it's ancient :-)

**Pull request merged**
